"""empty message

Revision ID: 1457f0fee23a
Revises: 3909d1877009
Create Date: 2021-01-08 19:59:25.042530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1457f0fee23a'
down_revision = '3909d1877009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_intake', 'nf_fats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intake', sa.Column('nf_fats', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
