"""empty message

Revision ID: 35fd60f3fbd6
Revises: 665f7b53d02c
Create Date: 2021-01-13 15:41:55.472938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fd60f3fbd6'
down_revision = '665f7b53d02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intake', sa.Column('nf_calcium_dv', sa.String(length=250), nullable=False))
    op.add_column('user_intake', sa.Column('nf_iron_dv', sa.String(length=250), nullable=False))
    op.add_column('user_intake', sa.Column('nf_total_carbohydrate', sa.String(length=250), nullable=False))
    op.add_column('user_intake', sa.Column('nf_vitamin_a_dv', sa.String(length=250), nullable=False))
    op.add_column('user_intake', sa.Column('nf_vitamin_c_dv', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_intake', 'nf_vitamin_c_dv')
    op.drop_column('user_intake', 'nf_vitamin_a_dv')
    op.drop_column('user_intake', 'nf_total_carbohydrate')
    op.drop_column('user_intake', 'nf_iron_dv')
    op.drop_column('user_intake', 'nf_calcium_dv')
    # ### end Alembic commands ###
