"""empty message

Revision ID: 3909d1877009
Revises: bdea63d52cad
Create Date: 2021-01-08 19:31:26.147189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3909d1877009'
down_revision = 'bdea63d52cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intake', sa.Column('item_name', sa.String(length=250), nullable=False))
    op.add_column('user_intake', sa.Column('nf_calories_from_fat', sa.String(length=250), nullable=False))
    op.create_foreign_key(None, 'user_intake', 'user', ['user_id'], ['id'])
    op.drop_column('user_intake', 'product_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intake', sa.Column('product_name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_constraint(None, 'user_intake', type_='foreignkey')
    op.drop_column('user_intake', 'nf_calories_from_fat')
    op.drop_column('user_intake', 'item_name')
    # ### end Alembic commands ###
