"""empty message

Revision ID: 583477e97690
Revises: 1457f0fee23a
Create Date: 2021-01-12 20:34:17.035863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583477e97690'
down_revision = '1457f0fee23a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intake', sa.Column('nf_total_fat', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_intake', 'nf_total_fat')
    # ### end Alembic commands ###
