"""empty message

Revision ID: 665f7b53d02c
Revises: 583477e97690
Create Date: 2021-01-12 20:48:15.899428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665f7b53d02c'
down_revision = '583477e97690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intake', sa.Column('nf_cholesterol', sa.String(length=250), nullable=False))
    op.add_column('user_intake', sa.Column('nf_trans_fatty_acid', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_intake', 'nf_trans_fatty_acid')
    op.drop_column('user_intake', 'nf_cholesterol')
    # ### end Alembic commands ###
