"""empty message

Revision ID: b8020917539e
Revises: 35fd60f3fbd6
Create Date: 2021-01-13 16:38:53.012149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8020917539e'
down_revision = '35fd60f3fbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_intake', sa.Column('nf_serving_size_qty', sa.String(length=250), nullable=False))
    op.add_column('user_intake', sa.Column('nf_serving_size_unit', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_intake', 'nf_serving_size_unit')
    op.drop_column('user_intake', 'nf_serving_size_qty')
    # ### end Alembic commands ###
