"""empty message

Revision ID: bdea63d52cad
Revises: 
Create Date: 2020-12-22 01:39:27.075730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdea63d52cad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=250), nullable=False),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_intake',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('nf_calories', sa.String(length=250), nullable=False),
    sa.Column('nf_protein', sa.String(length=250), nullable=False),
    sa.Column('nf_fats', sa.String(length=250), nullable=False),
    sa.Column('nf_saturated_fats', sa.String(length=250), nullable=False),
    sa.Column('nf_sugars', sa.String(length=250), nullable=False),
    sa.Column('nf_sodium', sa.String(length=250), nullable=False),
    sa.Column('nf_dietary_fiber', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_intake')
    op.drop_table('user')
    # ### end Alembic commands ###
